services:
  api:
    build: .
    container_name: jarvis_api
    ports:
      - "8000:8000"
    volumes:
      - ./.tmp:/app/.tmp
      - ./api:/app/api
      - ./tools:/app/tools
      - ./architecture:/app/architecture
    env_file:
      - .env
    depends_on:
      - ollama
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  ollama:
    image: ollama/ollama:latest
    container_name: jarvis_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      /bin/sh -c "
      /bin/ollama serve &
      sleep 5 &&
      /bin/ollama pull llama3.2 &&
      tail -f /dev/null
      "

volumes:
  ollama_data:
